### ISSUE TITLE
10 Print Example

### ISSUE THREAD

**Issue by ampersanda** [quil/quil-site#19]
http://quil.info/sketches/show/-KzO2S1X6sg1ce9WkPRE

It's not pretty good but maybe I can submit this

```
(ns my.core
  (:require [quil.core :as q :include-macros true]
            [quil.middleware :as m]))

(defn setup []
  (q/background 0)
  (q/frame-rate 30)
  (q/color-mode :hsb)
  {:x 0
   :y 0
:scale 20})

(defn update-state [{:keys [x y scale] :as state}]
  {:x (if (>= x (q/width)) 0 (+ x scale))
   :y (if (>= x (q/width)) (+ y scale) y)
   :scale scale})

(defn draw-state [{:keys [x y scale] :as state}]
  (q/stroke (* 255 (rand)) (* 255 (rand)) (* 255 (rand)))

  (if (>= y  (q/height))
    (q/no-loop)
    (if (> (rand) 0.5)
      (q/line x y (+ x scale) (+ y scale))
(q/line x (+ y scale) (+ x scale) y))))

(q/defsketch my
  :host "host"
  :size [500 500]
  :setup setup
  :update update-state
  :draw draw-state
  :middleware [m/fun-mode])
```

**Comment by nbeloglazov** [comment]
Thanks. It looks nice! I'm going to add it later (next week). Could you also update it so that it automatically starts over when it reaches last line? Currently after it reaches the last line it stops changing. Or instead of starting over do some other way to make it infinite.

**Comment by ampersanda** [comment]
I am currently read this, sorry. I just add some maybe "infinite" thing

**Comment by nbeloglazov** [comment]
Thank you @ampersanda for the sketch! I added your sketch and now it's available on quil.info: http://quil.info/?example=ten%20print

**Comment by ampersanda** [comment]
Thank you very much. I learn some of your code and that's amazing
