### ISSUE TITLE
15+ sec landing page load for an uncached visit

### ISSUE THREAD

**Issue by Nefry** [quil/quil-site#6]
Demos on the page are not visible for 15+ seconds for the uncached visit due to the main.js extremely long content download time.

Suggestions:
1) Add CDN
2) Show static light images for chosen animations with author before js fully loaded (no link to the sorce that just not working while js download)

![image](https://cloud.githubusercontent.com/assets/1214119/5544210/b4533c3a-8ab6-11e4-8221-eb020ff0146c.png)
![image](https://cloud.githubusercontent.com/assets/1214119/5544213/c229056a-8ab6-11e4-9a4e-7e97f4de837a.png)

**Comment by nbeloglazov** [comment]
Partially addressed by using reverse proxy that gzips and adds Cache-Control header that caches js responses for 1 hour.
